short_name: llm_teacher
namespace: qpy
version: 0.1.0
api_version: '0.1'
author: innoCampus <info@isis.tu-berlin.de>
name:
  de: LLM Lehrer
  en: LLM Teacher
description:
  de: Automatisiertes Feedback mittels KI. Bitte nur bei freiwilligen Abgaben nutzen. (experimentell)
  en: Automated feedback with AI. Please only use for voluntary submissions. (experimental)
languages:
  - de
  - en
requirements:
  - openai
  - pydantic
environment_variables:
  - OPENAI_API_KEY
  - OPENAI_BASE_URL
  - OPENAI_MODEL
